{% macro finalize_non_er_participants(entity_type) %}
{# For non-ER entities, participants are resolved by computing a deterministic
   entity_id from the source identifier, matching the ID generated by
   register_entities(). No entity resolution pipeline needed. #}

{% set entity_config = nexus.get_entity_type_config() %}
{% set type_config = entity_config[entity_type] %}
{% set reg_model = type_config.get('registration_model') %}

{% if reg_model %}
with entity_identifiers as (
  select * from {{ ref('nexus_entity_identifiers') }}
  where entity_type = '{{ entity_type }}'
),

registered_entities as (
  select entity_id, source_id
  from {{ ref(reg_model) }}
),

joined as (
  select
    reg.entity_id,
    ei.event_id,
    ei.role,
    ei.occurred_at
  from entity_identifiers ei
  inner join registered_entities reg
    on ei.identifier_value = reg.source_id
)

select
  {{ nexus.create_nexus_id('entity_participant', ['event_id', 'entity_id', 'role']) }} as entity_participant_id,
  '{{ entity_type }}' as entity_type,
  event_id,
  entity_id,
  role,
  occurred_at
from joined
group by event_id, entity_id, role, occurred_at
{% else %}
select
  cast(null as string) as entity_participant_id,
  cast(null as string) as entity_type,
  cast(null as string) as event_id,
  cast(null as string) as entity_id,
  cast(null as string) as role,
  cast(null as timestamp) as occurred_at
where 1 = 0
{% endif %}
{% endmacro %}
